### ISSUE TITLE
S1: As an unregistered user, I want to be able to register as a user with my chosen credentials (i.e., username and password that are both not empty words) to leverage/use services and information that are exclusively available to registered users.

### ISSUE THREAD

**Issue by ABacmann** [sopra-fs23-group-4/sopra-fs23-group-04-server#1]
# Development Tasks

Frontend

- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#4

- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#5

- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#6

- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#7

Backend

- [x] #76

- [x] #77

- [x] #78

- [x] #79

- [x] #80

- [x] #81

- [x] #82

**Comment by ABacmann** [comment]
# Development Tasks

Frontend

- [ ]     Add file structure for client side 

- [ ]     Implement a common layout template 

- [ ]     Implement a button template 

- [ ]     Implement a login page with guard 

- [ ]     Implement a registration page with guard 

Backend

- [ ]     Add file structure for client side 

- [ ]     Add empty profile picture 

- [ ]     Create user entity, userPostDTO (add tests) 

- [ ]     Create mapping for user registration and login (add tests) 

- [ ]     Create userController for the login and registration (add tests) 

- [ ]     Create userService function to save user to DB, add creationDate, add standard profilePicture, autogenerate and add quote (add tests) 

- [ ]     Create userService to retrieve a user from the DB (add tests)
