### ISSUE TITLE
S10: As a player I want to see a voting page where I can go through the categories one by one with the other players and see all given answers (anonymously). We are then able to vote on the correctness and uniqueness of the answers.

### ISSUE THREAD

**Issue by ABacmann** [sopra-fs23-group-4/sopra-fs23-group-04-server#10]
# Development Tasks

Frontend

- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#24

- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#25

- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#26

Backend

- [x] sopra-fs23-group-4/sopra-fs23-group-04-server#118

- [x] sopra-fs23-group-4/sopra-fs23-group-04-server#119

- [x] sopra-fs23-group-4/sopra-fs23-group-04-server#120

**Comment by ABacmann** [comment]
# Development Tasks

Frontend

- [ ]     Add a voting page where one category is shown with all the answers (of other players) 

- [ ]     Add selection button template 

- [ ]     Add a voting overview page where one category is shown with all the answers and the votes 

Backend

- [ ]     Add funcitonality to save the voting and points from a specific category in a game to the game entity, gameController and gameService (add tests) 

- [ ]     Add websockets to control voting flow with timer 

- [ ]     With websockets send random fact to frontend at the end of the voting, redirect to scoreboard
