### ISSUE TITLE
S11: As user I want to see a winner scoreboard with final score after the game is finished to see how every player performed.

### ISSUE THREAD

**Issue by ABacmann** [sopra-fs23-group-4/sopra-fs23-group-04-server#11]
# Development Tasks

Frontend

- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#27

- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#28

Backend

- [x] sopra-fs23-group-4/sopra-fs23-group-04-server#123

- [x] sopra-fs23-group-4/sopra-fs23-group-04-server#124

**Comment by ABacmann** [comment]
# Development Tasks

Frontend

- [ ]     Add a scoreboard page where the players are displayed in order of their score, display a random fact add a button to start next round 

- [ ]     Add winner page 

Backend

- [ ]     With websockets send users of the game in order of their score and a random fact which is generated by the api 

- [ ]     With websockets notify the frontend if it’s the last round and only send winner
