### ISSUE TITLE
S17: As a user I want to be able to see a leaderboard of the top ten player and my position, so I know my overall position

### ISSUE THREAD

**Issue by ABacmann** [sopra-fs23-group-4/sopra-fs23-group-04-server#174]
Frontend

- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#37
- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#38
- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#39
- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#40

Backend

- [x] sopra-fs23-group-4/sopra-fs23-group-04-server#179
- [x] sopra-fs23-group-4/sopra-fs23-group-04-server#180
- [x] sopra-fs23-group-4/sopra-fs23-group-04-server#181

**Comment by ABacmann** [comment]
Frontend

- [ ] create a button from the dashboard to link to the leaderboard page
- [ ] implement a Get Rest call to get the leaderboard from the backend
- [ ] create the design (show top ten players and if the user is not part of it, its overall position)
- [ ] add back button than link back to the dashboard

Backend

- [ ] create leaderboard endpoint in GameController
- [ ] create a LeaderboardGetDTO class with username and score
- [ ] implement a method to fetch all the user and sort them according to their points (Top-down)

**Comment by ABacmann** [comment]
- [ ] g
