### ISSUE TITLE
S7:  As a player I want to see the letter of the round to be prepared.

### ISSUE THREAD

**Issue by ABacmann** [sopra-fs23-group-4/sopra-fs23-group-04-server#7]
# Development Tasks

Frontend

- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#19

Backend

- [x] sopra-fs23-group-4/sopra-fs23-group-04-server#107

- [x] sopra-fs23-group-4/sopra-fs23-group-04-server#108

**Comment by ABacmann** [comment]
# Development Tasks

Frontend

- [ ]     Implement a start game page (create and join options) 

- [ ]     Implement a lobby page 

Backend

- [ ] 

- [ ]
