### ISSUE TITLE
S8:  As a player I want to see a categories overview (which are buttons) where I can select a category to input my answer.

### ISSUE THREAD

**Issue by ABacmann** [sopra-fs23-group-4/sopra-fs23-group-04-server#8]
# Development Tasks

Frontend

- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#20

- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#21

- [x] sopra-fs23-group-4/sopra-fs23-group-04-client#22

Backend

- [x] sopra-fs23-group-4/sopra-fs23-group-04-server#112
